# Generated by Django 4.1.2 on 2022-10-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materiasportal',
            fields=[
                ('id_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('dt_materia', models.DateField(blank=True, null=True)),
                ('link_materia', models.TextField(blank=True, null=True)),
                ('titulo_materia', models.TextField(blank=True, null=True)),
                ('texto_materia', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'materiasportal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Portalcnn',
            fields=[
                ('id_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('dt_hr_pesquisa', models.DateTimeField(blank=True, null=True)),
                ('nome_sessao', models.CharField(blank=True, max_length=100, null=True)),
                ('link_site', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'portalcnn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogServicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_hr_exec_func', models.DateTimeField(null=True)),
            ],
        ),
    ]
