# Generated by Django 4.1.2 on 2022-10-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logservicos',
            name='func_portal',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
