# Generated by Django 4.1.2 on 2022-10-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_logservicos_func_portal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiasportalcnn',
            fields=[
                ('id_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('dt_materia', models.DateField(blank=True, null=True)),
                ('link_materia', models.TextField(blank=True, null=True)),
                ('titulo_materia', models.TextField(blank=True, null=True)),
                ('texto_materia', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'materiasportalcnn',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Materiasportal',
        ),
    ]
