# Generated by Django 4.1.2 on 2022-11-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_materiasportalcnn_delete_materiasportal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiasportalg1',
            fields=[
                ('id_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('dt_materia', models.DateField(blank=True, null=True)),
                ('link_materia', models.TextField(blank=True, null=True)),
                ('titulo_materia', models.TextField(blank=True, null=True)),
                ('texto_materia', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'materiasportalg1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Portalg1',
            fields=[
                ('id_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('dt_hr_pesquisa', models.DateTimeField(blank=True, null=True)),
                ('nome_sessao', models.CharField(blank=True, max_length=100, null=True)),
                ('link_site', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'portalg1',
                'managed': False,
            },
        ),
    ]
