# Generated by Django 4.1.3 on 2022-11-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_materiasportalg1_portalg1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiasportaluol',
            fields=[
                ('id_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('dt_materia', models.DateField(blank=True, null=True)),
                ('link_materia', models.TextField(blank=True, null=True)),
                ('titulo_materia', models.TextField(blank=True, null=True)),
                ('texto_materia', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'materiasportaluol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Portaluol',
            fields=[
                ('id_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('dt_hr_pesquisa', models.DateTimeField(blank=True, null=True)),
                ('nome_sessao', models.CharField(blank=True, max_length=100, null=True)),
                ('link_site', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'portaluol',
                'managed': False,
            },
        ),
    ]
